export type EventAction =
  | 'audio-player-play-event'
  | 'audio-player-30-seconds-listened'
  | 'audio-player-listened'
  | 'goto-seasons'
  | 'goto-specials'
  | 'goto-about'
  | 'goto-season'
  | 'goto-episode'
  | 'goto-special'
  | 'playerlist-open'
  | 'playerlist-close'
  | 'player-closed'
  | 'main-slider-goto-season'
  | 'main-slider-goto-episode'
  | 'main-slider-goto-special'
